version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:80"
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
